linters:
  enable-all: true
  disable:
    - maligned
    - prealloc
    - gochecknoglobals
    - vetshadow
    - errcheck
    - gocyclo
    - goconst
    - gas
    - gosec
    - lll
    - dupl
    - goimports
linters-settings:
  #govet:
    #check-shadowing: true
    #settings:
      #printf:
        #funcs:
          #- (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          #- (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          #- (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          #- (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  golint:
      min-confidence: 0
  gocyclo:
    min-complexity: 10
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  depguard:
    list-type: blacklist
    packages:
      # logging is allowed only by logutils.Log, logrus
      # is allowed to use only in logutils package
      - github.com/sirupsen/logrus
  misspell:
    locale: US
    ignore-words:
        cancelled
  lll:
    line-length: 140
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - commentFormatting
        #- dupImport # https://github.com/go-critic/go-critic/issues/845
