# vim: ft=sh
# Configuration file for slack_status
TOKEN=xoxp-000000000000-000000000000-0000000000000-00000000000000000000000000000000

PRESET_EMOJI_test=":white_check_mark:"
PRESET_TEXT_test="Testing status updater"

PRESET_EMOJI_zoom=":phone:"
PRESET_TEXT_zoom="In a zoom meeting"
